- README.md
Badge was still pointing to module template build
> build: fix ci badge

- .github/workflows/ci.yml
- .github/workflows/release.yml
- .releaserc
- Pass "false" into `run-catalog-onboarding-pipeline.sh` as arg 10 (which is `useCatalogSource`) to force release using default tar.gz file (not catalog refs)
- bump latest git submodule
- bump latest pipeline
> ci: dont use catalog as source

- examples/basic/version.tf
- examples/override-example/version.tf
- examples/quickstart/version.tf
- patterns/mixed/versions.tf
- patterns/roks/versions.tf
- patterns/vsi/versions.tf
Lock in ibm provider version to 1.45.1 for the patterns
> feat: ibm provider version locked into 1.45.1 for patterns

- patterns/vsi/catalogValidationValues.json.template
set `override_json_string` to "__NOT_SET__" in json template
> ci: set override_json_string to "__NOT_SET__" in json template

- f5_config/main.tf
- f5_config/outputs.tf
- f5_config/versions.tf
- module-metadata.json
- patterns/dynamic_values/config_modules/acl_rules/acl_rules.tf
- patterns/dynamic_values/config_modules/network_acls/network_acls.tf
- teleport_config/outputs.tf
- teleport_config/template.tf
- teleport_config/versions.tf
template_file is deprecated and does not work with M1 machines.  Move to templatefile
> fix: template module deprecated and f5 acl name

- tests/other_test.go
- tests/pr_test.go
Change unit tests to use a shared CloudInfoService object so that all parallel tests will pick unique regions.
Test changes only
---
> test: use shared info svc to guarantee unique regions

- README.md
- examples/no-compute-example/README.md
- examples/quickstart/README.md
- patterns/roks/README.md
- patterns/vsi/README.md
- Changing the image URLs for the readme files that are pulled in the IBM Cloud catalog. Relative links produce broken images there.
- Updating text to provide a bit more information in the context of the catalog details.
---
> docs: use absolute links for images

- .secrets.baseline
- examples/no-compute-example/catalogValidationValues.json.template
- ibm_catalog.json
- patterns/vpc/catalogValidationValues.json.template
- patterns/vpc/override.json
- set ssh_keys to empty list in pvc pattern override json
- update `ibm_catalog.json` to use `patterns/vpc`
- added the variables to hide for VPC pattern in `ibm_catalog.json`
- fix the values in `patterns/vpc/catalogValidationValues.json.template`
- deleted `examples/no-compute-example/catalogValidationValues.json.template`
---
The commit message determines whether …
> fix: set ssh_keys to empty list in pvc pattern override json

- dynamic_values/config_modules/service_authorizations/service_authorizations.tf
- moved_config.tf
Plan shows the following:
module.landing_zone.ibm_iam_authorization_policy.policy["flow-logs-atracker-cos-cos"] will be created
Removed the duplicate string `-cos` from the policy name
Issue : https://github.com/terraform-ibm-modules/terraform-ibm-landing-zone/issues/412
Removed the duplicate substring `-cos` from the policy name
---
> fix: remove duplicate substring from policy name

- patterns/roks/catalogValidationValues.json.template
Looks like cost generator tool is broken for eu-gb, as it shows 0 cost for OCP:
---
> ci: set catalog validation for roks DA to use us-south

- patterns/roks/catalogValidationValues.json.template
Reverts terraform-ibm-modules/terraform-ibm-landing-zone#421
The issue is resolved, so setting back to use `eu-gb` to ensure we don't hit transit gateway quotas in us-south
> Revert "ci: set catalog validation for roks DA to use us-south"

- tests/pr_test.go
re-enabled roks and vsi pattern tests in SLZ using Key Protect instead of HPCS
Run the CI pipeline when the PR is ready …
> [Tests] re-enable roks and vsi pattern tests in SLZ using Key Protect instead of HPCS

- examples/one-vpc-one-vsi/version.tf
- examples/override-example/version.tf
- patterns/mixed/versions.tf
- patterns/roks/versions.tf
- patterns/vpc/version.tf
- patterns/vsi-quickstart/version.tf
- patterns/vsi/versions.tf
update DA IBM provider versions to 1.56.1 to pull in fix for https://github.com/IBM-Cloud/terraform-provider-ibm/pull/4755
```
/run pipeline
```
> fix(deps) update DAs IBM provider version to 1.56.1

- ibm_catalog.json
- patterns/roks/module/variables.tf
- patterns/roks/variables.tf
- Update the ssh key related variable descriptions for the OCP pattern (DA)
- Hide the `existing_ssh_key_name` variable from catalog since all of the F5 and Bastion variables are hidden. (NOTE: `ssh_public_key` is already hidden but seems `existing_ssh_key_name` was missed).
```
/run pipeline
```
- When merging, use a relevant [conventional commit](https://www.conventionalcommits.org/) message that is based on the PR contents and any release notes provided by the PR author. The commit message determines whether a new version of …
> fix: update the ssh key related variable descriptions for the OCP pattern

- tests/other_test.go
The region `jp-osa` is currently not allowing hs-crypto keys to be used for COS bucket encryption (server side). When that region is selected as the best region to run the HPCS unit tests, those tests will fail.
If `jp-osa` is chosen as the best region for HPCS tests, we will now default back to region `us-south` instead.
The region `jp-osa` is currently not allowing hs-crypto keys to be used for COS bucket encryption (server side). Unit tests have been updated to make sure this region is not used for any HPCS tests.
```
/run …
```
> test: do not use jp-osa region for HPCS tests

- examples/one-vpc-one-vsi/main.tf
- examples/one-vpc-one-vsi/version.tf
- examples/override-example/main.tf
- examples/override-example/version.tf
- patterns/mixed/versions.tf
- patterns/roks/versions.tf
- patterns/vpc/version.tf
- patterns/vsi-extension/version.tf
- patterns/vsi-quickstart/version.tf
- patterns/vsi/versions.tf
bump ibm tf provider version to 1.59.0 for all SLZ DAs to pick up fixes around private OCP cluster certs
```
/run pipeline
```
> fix(deps): bump ibm tf provider version to 1.59.0 for all SLZ DAs

- ibm_catalog.json
As per [docs](https://cloud.ibm.com/docs/secure-enterprise?topic=secure-enterprise-manifest#catalog-manifest-create), look like you can add "release_notes_url" into each flavor specified in ibm_catalog.json
```
/run pipeline
```
- Use the …
> ci: add "release_notes_url" to ibm_catalog.json

- tests/other_test.go
Disabling the creation of the HyperProtect-Block Storage auth policy for the two HPCS tests, to avoid conflicts with existing policies in test account.
```
/run pipeline
```
> test: disable policy create for hpcs tests

- tests/other_test.go
- tests/pr_test.go
Due to issues with resource group deletion (reclamation issues), this change will cause all unit tests to ignore `destroy` of resource groups created by using the `ImplicitDestroy` feature of `ibmcloud-terratest-wrapper`, which will remove the resource groups from terraform state before `destroy`.
Because there is no `ImplicitDestroy` feature for Schematics tests, those unit tests have been moved from PR tests into the "Other" tests so that this resource group delete issue does not block pull requests.
```
/run pipeline
```
- Use …
> test: ignore resource group destroy

- dynamic_values/config_modules/service_authorizations/service_authorizations.tf
- dynamic_values/service_authorizations.tf
Addded kube to KMS auth policy creation.
```
/run pipeline
```
> fix: kube to kms auth policy creation

- .secrets.baseline
- kms/main.tf
In order to set endpoint type for Key Protect, you have to pass it as a parameter like this:
```
parameters = {
allowed_network: "public-and-private",
}
```
It should not be passed directly into `ibm_resource_instance` like we are doing now, as it is a special case.
```
/run pipeline
```
- Include information that users need to know about the PR in the commit message. The commit …
> fix: fix the way service endpoint type is passed to Key Protect

- patterns/mixed/override.json
- patterns/roks/override.json
- patterns/vpc/override.json
- patterns/vsi/override.json
> fix: update default values inside override.json

- tests/pr_test.go
In [v5.17.1](https://github.com/terraform-ibm-modules/terraform-ibm-landing-zone/releases/tag/v5.17.1) the `service_endpoints` var was removed from all patterns, but the tests were not updated. Fixed in this PR
```
/run pipeline
```
- Use …
> Update pr_test.go to stop passing in invalid var

- patterns/roks-quickstart/main.tf
- patterns/roks-quickstart/variables.tf
- tests/pr_test.go
This change will add a new input variable to `patterns/roks-quickstart` for the field "cluster entitlement" which will allow consumers to specify a specific entitlement or leave null if their account does not have any entitlements (was previously set to "cloud_pak").
```
/run pipeline
```
- Include information that users need to know about the PR in the commit message. The …
> fix: expose cluster entitlement variable for OCP quickstart

- atracker.tf
- variables.tf
Added eu-fr2 in the supported regions for Atracker route creation and regional COS
https://github.com/terraform-ibm-modules/terraform-ibm-landing-zone/issues/773
Added eu-fr2 in the supported regions for Atracker route creation and regional COS
```
/run pipeline
```
- Include information that users need to know about the PR in the commit message. The commit message becomes part …
> feat: added eu-fr2 support in atracker and cos

- patterns/roks-quickstart/main.tf
- remove duplicate `kms_config` from OCP quickstart override json as `kms_config` is set later in the json
```
/run pipeline
```
> remove duplicate `kms_config` from OCP quickstart override json

- .catalog-onboard-pipeline.yaml
Update .catalog-onboard-pipeline.yaml to use projects again for validation since the timeout issue we had been seen has been fixed in prod
```
/run pipeline
```
> Update .catalog-onboard-pipeline.yaml to use projects again for validation

- examples/one-vpc-one-vsi/override.json
- examples/override-example/override.json
- patterns/mixed/override.json
- patterns/mixed/variables.tf
- patterns/roks/module/variables.tf
- patterns/roks/variables.tf
- patterns/vpc/module/variables.tf
- patterns/vpc/variables.tf
- patterns/vsi-extension/variables.tf
- patterns/vsi-quickstart/variables.tf
- patterns/vsi/module/variables.tf
- patterns/vsi/override.json
- patterns/vsi/variables.tf
Update VSI image name variable defaults to ibm-ubuntu-24-04-minimal-amd64-2
> fix: update the default VSI image name to ibm-ubuntu-24-04-minimal-amd64-2

- outputs.tf
https://github.com/terraform-ibm-modules/terraform-ibm-landing-zone/issues/851
landing-zone output `resource_group_names` does not contain proper values
https://github.com/terraform-ibm-modules/terraform-ibm-landing-zone/blob/14b3656b0787f7da81163a98726b739a90b20ca1/resource_groups.tf#L42
https://github.com/terraform-ibm-modules/terraform-ibm-landing-zone/blob/14b3656b0787f7da81163a98726b739a90b20ca1/outputs.tf#L274
fix for landing-zone output `resource_group_names` does not containing proper values
```
/run pipeline
```
- Use a …
> fix: resource group names

- README.md
- outputs.tf
- patterns/roks/module/outputs.tf
- patterns/roks/outputs.tf
Added new outputs for OCP cluster names (workload and management) to support new Projects stacks.
```
/run pipeline
```
> fix: added outputs for cluster names

- ibm_catalog.json
Updated VSI extension DA to explicitly have hard dependency on VPC landing zone DA. Although currently catalog is defaulintg to optional: true, in the next push to prod, it will be optional by default
```
/run pipeline
```
- Use the …
> Updated VSI extension DA to explicitly have hard dependency on VPC landing zone DA

- patterns/roks/main.tf
- patterns/roks/module/config.tf
- patterns/roks/module/variables.tf
- patterns/roks/variables.tf
Added a new input parameter `ignore_vpcs_for_cluster_deployment` (list of strings) that can be supplied in the ROKS pattern by a consumer that will configure landing zone to ignore certain VPCs for deploying clusters.
Added a new input parameter `ignore_vpcs_for_cluster_deployment` to the roks pattern to allow consumer to ignore specific VPCs for deploying clusters.
```
/run pipeline
```
- Use a conventional commit message to set the release level. Follow the [guidelines](https://terraform-ibm-modules.github.io/documentation/#/merg …
> feat: roks pattern - add option to ignore vpcs for clusters

- ibm_catalog.json
Added the IAM API Key Creator role to the needed permissions for ROKS patterns in the ibm_catalog.json configuration.
```
/run pipeline
```
> docs: add api key creator to catalog roks permissions

- ibm_catalog.json
Even though the default was set to 4.16 in variables.tf - it was not updated in ibm_catalog.json meaning the tile was never updated. I am removing the default value from the catalog manifest to prevent this from happening again, which means it will always use the default value in the terraform code.
```
/run pipeline
```
- Include information that users need to know about the PR …
> Update OCP default to 4.16

- cra-config.yaml
- ibm_catalog.json
- patterns/roks-quickstart/provider.tf
- patterns/roks-quickstart/variables.tf
- patterns/roks/main.tf
- patterns/roks/variables.tf
- patterns/vpc/main.tf
- patterns/vpc/variables.tf
- patterns/vsi-extension/provider.tf
- patterns/vsi-extension/variables.tf
- patterns/vsi-quickstart/provider.tf
- patterns/vsi-quickstart/variables.tf
- patterns/vsi/main.tf
- patterns/vsi/variables.tf
- tests/other_test.go
- tests/pr_test.go
This reverts commit a6c87a4142f275a2bbbece76bc51cdc3129a0ca9. and plugs test gaps mentioned in [issue](https://github.com/terraform-ibm-modules/terraform-ibm-landing-zone/issues/928)
reverts the ability to expose provider_visibility as there is a bug when setting the provider visibility to private related to resource tags and also plugs test gaps related to it
```
/run pipeline
```
- Use a conventional commit message to set the release level. Follow the [guidelines](https://terraform-ibm-modules.github.io/documentation/#/merging.md …
> Revert "feat: exposed the ability to set the `provider_visibility` in DA" and plugged test gaps

- README.md
- outputs.tf
- patterns/mixed/outputs.tf
- patterns/roks-quickstart/outputs.tf
- patterns/roks/module/outputs.tf
- patterns/roks/outputs.tf
- patterns/vpc/module/outputs.tf
- patterns/vpc/outputs.tf
- patterns/vpc/variables.tf
- patterns/vsi/module/outputs.tf
- patterns/vsi/outputs.tf
add new rg output for workload cluster
add new resource group id output for workload cluster
```
/run pipeline
```
> feat: add new rg id output

- examples/override-example/main.tf
- examples/override-example/variables.tf
- outputs.tf
- patterns/vsi/module/outputs.tf
- patterns/vsi/outputs.tf
- tests/other_test.go
- tests/pr_test.go
- tests/resources/override-example.json
Issue: https://github.com/terraform-ibm-modules/terraform-ibm-landing-zone/issues/936
```
/run pipeline
```
> fix: output error when management or workload rg are not present.

- atracker.tf
- main.tf
- service_authorizations.tf
Added a reference to the `time_sleep` resource of bucket auth polices to the VPC Module input for flow log bucket, to implicitly force the flow logs to wait for all bucket auth policies to complete first.
This fixes a random timing issue in which flow logs are getting set up slightly before the auth policy for buckets are finished.
```
/run pipeline
```
- Include information …
> fix: force vpc flow logs to wait for auth policy sleep

- cos.tf
add missing `endpoint_type` to the `ibm_cos_bucket_lifecycle_configuration`
```
/run pipeline
```
> fix: add missing `endpoint_type` to the `ibm_cos_bucket_lifecycle_configuration`
