terraform-ibm-modules/terraform-ibm-landing-zone

- .gitmodules
- .pre-commit-config.yaml
- .releaserc
- .secrets.baseline
- Brewfile
- Makefile
- ci
- commitlint.config.js
- renovate.json
This is an initial update adding in the `common-dev-assets` submodule and additional CI related files including symlinks to common build files.
> chore: added common dev files and symlinks

- examples/vsi-quickstart/main.tf
- examples/vsi-quickstart/variables.tf
- tests/pr_test.go
> fix: Update example to support tests

- tests/pr_test.go
> fix: skip upgrade test for init PR

- landing-zone/atracker.tf
- tests/go.mod
> fix: atracker v2

- catalogValidationValues.json.template
> fix: address missing catalog template file

- version.tf
> build: update required version format

- README.md
> build: version fix with precommit

- .releaserc
- README.md
> Fix releaserc

- .releaserc
- .secrets.baseline
- ibm_catalog.json
Modify catalog publishing for this offering to now publish to a different offering (new) in the catalog.
Also including a catalog manifest file, ibm_catalog.json, to specify the current flavor name.
- [x ] CI related update (pipeline, etc.)
> ci: publish to new offering and use a catalog manifest file

- appid.tf
- kms/main.tf
- kms/variables.tf
- main.tf
- outputs.tf
- patterns/dynamic_values/config_modules/key_management/key_management.tf
- patterns/dynamic_values/outputs.tf
- patterns/mixed/config.tf
- patterns/roks/config.tf
- patterns/vsi/config.tf
- resource_groups.tf
- secrets_manager.tf
- services.tf
- virtual_servers.tf
- vpe.tf
> feat: update module with recent updates

- README.md
- outputs.tf
- variables.tf
Add output for all vsi's which includes name, id, zone, and primary ipv4 address, VPC Name, and floating IP.  Also, fix a roks validation for duplicate names
> feat: output all vsi info and fix roks var validation

- .secrets.baseline
- ibm_catalog.json
This change updates the ibm_catalog.json file so that a new variation is named from directory "patterns/vsi" in the repo.
Note: A possible change is needed in the publishing pipeline to import this variation and validate it.
> build: update catalog json file to identify a Standard variation

- tests/pr_test.go
Enable upgrade test - checking backward compatibility now that override example is on main branch.
> test: enable override upgrade test

- ibm_catalog.json
Update catalog json file to use the github urls for the architecture diagrams.
- [x ] Documentation update
> docs: use github urls for diagrams in catalog json

- ibm_catalog.json
This is an update to the description text for the architecture diagram that was provided by the Content team.  Checking it to keep it from getting lost.
- [x ] Documentation update
> docs: fold in Content updates for description

- patterns/vsi/outputs.tf
This change allows the output of additional values that are needed for other solutions.
> feat: additional outputs for solutions

- .releaserc
> ci: fix typo in .releaserc

- ibm_catalog.json
Flavor name cannot have an embedded space char.
> docs: flavor name cannot have a space in it

- examples/quickstart/pre-validation.sh
- patterns/vsi/pre-validation.sh
> ci: use -r flag with jq for pre-validation catalog script

- patterns/mixed/outputs.tf
- patterns/mixed/variables.tf
- patterns/roks/outputs.tf
- patterns/roks/variables.tf
- patterns/vsi/outputs.tf
- patterns/vsi/variables.tf
> feat: add schematics workspace output

- .docs/bastion/bastion.md
- .docs/f5-big-ip/f5-big-ip.md
- .docs/pattern-defaults.md
- .docs/patterns/mixed-pattern.md
- .docs/patterns/roks-pattern.md
- .docs/patterns/vsi-pattern.md
- README.md
This PR merges into the customization-docs branch and updates the docs in the open PR https://github.com/terraform-ibm-modules/terraform-ibm-landing-zone/pull/123/.
❗ **Important:** I replaced a couple of references to the `tfvars` file with the `variables.tf` file in the main readme file.
> docs: update 2nd drop for slz

- README.md
update github ref syntax in readme
> docs: update github refs

- .docs/bastion/bastion.md
- .docs/f5-big-ip/f5-big-ip.md
Remove allowlist aspects as all fscloud doc is public at this stage
> docs: update bastion doc

- patterns/vsi/catalogValidationValues.json.template
Remove value for `override_json_string` in catalogValidationValues.json.template for vsi pattern. Its not longer marked as a required value in the offering
> ci: update catalogValidationValues.json.template

- .github/settings.yml
> Using to trigger settings bot

- .github/settings.yml
> docs: add description for landing zone

- kms/variables.tf
- outputs.tf
- ssh_key/variables.tf
- variables.tf
Fix terraform_deprecated_index tflint rule
> fix: address tflint terraform_deprecated_index rule

- ibm_catalog.json
Minor cleanup of usage property to remove unicode character of the ampersand and use the ampersand char directly.
> docs: minor cleanup to usage, remove unicode value

- .releaserc
- patterns/roks/catalogValidationValues.json.template
Changes required to onboard roks tile to catalog. Purposely using `feat` so we create a new minor release for this
> feat: onboard roks tile to catalog

- patterns/roks/variables.tf
> fix: limit prefix roks variable to 13 characters

- ibm_catalog.json
Small update for the usage statement for the ROKS variation.  Includes a range this time but we are looking at better ways to deal with this so that it does not need updating as often.  
> docs: update the semver for roks in usage

- .secrets.baseline
- ibm_catalog.json
add type image spec to architecture diagrams in catalog json
- [x ] CI related update (pipeline, etc.)
> ci: fix architecture image spec in catalog manifest

- ibm_catalog.json
Reviewed features and IAM permissions and made the some updates to make them correct.  Previously they were a copy of the VSI pattern so now they are ROKS specific where needed.
- [x ] Documentation update
> docs: update catalog features and IAM permissions for ROKS

- README.md
Merges into PR #175.
Updated links, used standard terminology and product names, and tried to simplify the information.
> docs: editorial updates to readme

- patterns/roks/README.md
> docs: fix title

- ibm_catalog.json
It's not currently possible to use ${{version}} in the `diagram` section so need to lock into main for now. Opened enhancement request for catalog to support this. 
---
> docs: update main refs in ibm_catalog.json

- ibm_catalog.json
The usage template incorrectly had the flavor name as the "kind" within the URL.  Fixed.
Also removed catalogId on OCP flavor since it will be published.
---
> docs: specify correct kind within usage

- reference-architectures/deploy-arch-ibm-slz-ocp.md
- reference-architectures/deploy-arch-ibm-slz-vsi-quickstart.md
- reference-architectures/deploy-arch-ibm-slz-vsi-standard.md
- Rename to match updated names
- Update from review by Adam and Jennifer in IBM Cloud Docs:
> Components section...
> 
> * Take out the **Edge VPC** since there is no edge
> * Take out _Create a virtual server instance that can act as an internet proxy server_ row and add **Create a virtual server instance to run your workload**
> * Take out **Create a virtual server instance to host basic management services like DNS, NTP, NFS**
---
- Use a relevant [conventional commit](https://www.conventionalcommits.org/) message that is …
> docs: update ref arch after review in cloud

- .secrets.baseline
- ibm_catalog.json
There has been some changes since we first discussed a couple of properties in the manifest file.
"is_full_stack" is now "install_type" and has a value of "extension" or "fullstack".
Also the property "product_kind" with a value of "solution" (which denotes a deployable architecture) was added.
This is step 1 and the barest minimum changes needed for the manifest file.  
The catalog milestone that delivers on April 4th uses the above properties and more.
---
- Use a relevant [conventional …
> docs: update manifest with current solution properties

- reference-architectures/deploy-arch-ibm-slz-vpc-standard.md
Updates from Adam's comments in https://github.com/terraform-ibm-modules/terraform-ibm-landing-zone/pull/327 after it was merged
Adam had a question about line 83
> I am not sure what network access is there by default since it looks like some updates. @ocofaigh / @vburckhardt do you know?
| Requirement | Component | Reasons for choice | Alternative choice |
|-------------|-----------|--------------------|--------------------|
| * Provide infrastructure/application administration access to monitor, operate, and maintain the environment.  \n * Limit the number of infrastructure/application administration entry points to ensure security audit. | Management VPC service | Create a separate VPC service where SSH connectivity from outside is allowed | |
Replace this text with information that …
> update vpc reference architecture

- cra-tf-validate-ignore-goals.json
- reference-architectures/deploy-arch-ibm-slz-ocp.md
- reference-architectures/deploy-arch-ibm-slz-vpc-standard.md
- reference-architectures/deploy-arch-ibm-slz-vsi-quickstart.md
- reference-architectures/deploy-arch-ibm-slz-vsi-standard.md
Add the deployment URL to the reference architectures to turn on the "Config and deploy" button in Cloud Docs
---
> docs: add deploy url

- reference-architectures/deploy-arch-ibm-slz-ocp.md
- reference-architectures/deploy-arch-ibm-slz-vpc-standard.md
- reference-architectures/deploy-arch-ibm-slz-vsi-quickstart.md
- reference-architectures/deploy-arch-ibm-slz-vsi-standard.md
Add `download` attribute to reference architectures so that the diagram is downloadable in Cloud Docs.
---
> docs: add download attribute

- .secrets.baseline
- ibm_catalog.json
Slimmed down version of previous PR whereby this PR captures only the variable customizations within the manifest instead of the full definition of each variable.  All variables retained so that order is preserved but much less to manage here.
---
The commit message determines whether a new version of the module is needed, and if so, which …
> docs: capture only variable customizations in manifest

- .github/workflows/ci.yml
- .github/workflows/release.yml
- cra-tf-validate-ignore-goals.json
remove `3000451` from cra-tf-validate-ignore-goals.json
---
> ci: remove 3000451 from cra-tf-validate-ignore-goals.json

- reference-architectures/deploy-arch-ibm-slz-ocp.md
- reference-architectures/deploy-arch-ibm-slz-vpc-standard.md
- reference-architectures/deploy-arch-ibm-slz-vsi-quickstart.md
- reference-architectures/deploy-arch-ibm-slz-vsi-standard.md
- Add `toc-version` attribute for Cloud Docs use.
- Remove HTML comments
- Remove FedRAMP compliance from QuickStart
- Remove email from authors metadata.
---
> docs: update reference architectures

- .releaserc
use `--destroy_on_failure` in catalog pipeline trigger script to ensure resources do not take up our quota limits
---
> ci: use --destroy_on_failure in catalog pipeline trigger script

- reference-architectures/deploy-arch-ibm-slz-ocp.md
- reference-architectures/deploy-arch-ibm-slz-vpc-standard.md
- reference-architectures/deploy-arch-ibm-slz-vsi-quickstart.md
- reference-architectures/deploy-arch-ibm-slz-vsi-standard.md
- VPC: Remove key and password management section because SSH was removed
- VSI standard and ROKs: update compliance statement per Tony E.
- Update version of reference architectures to match current catalog version
---
> docs: updates to ref arch

- reference-architectures/deploy-arch-ibm-slz-ocp.md
- reference-architectures/deploy-arch-ibm-slz-vpc-standard.md
- reference-architectures/deploy-arch-ibm-slz-vsi-quickstart.md
- reference-architectures/deploy-arch-ibm-slz-vsi-standard.md
Adds a new boolean flag `production` to the yaml metadata, which determines whether the RA is published to production.
---
> add docs metadata to reference architectures

- .secrets.baseline
- ibm_catalog.json
Removed some compliance controls in the catalog config for VSI and VPC patterns that are not supported at this time
---
> fix: remove catalog compliance controls in VSI/VPC patterns

- .secrets.baseline
- ibm_catalog.json
Matches the product details that were entered manually in partner center. You can verify them at the links in Hari's URLs box note
---
> Update product details

- tests/pr_test.go
Added test against pattern/vpc
---
> test: adds vpc pattern testing

- README.md
- ibm_catalog.json
PR to generate 3.7.0 release (which is based on the code that was merged in https://github.com/terraform-ibm-modules/terraform-ibm-landing-zone/pull/423) (See `Release notes content` below)
Also removed `ssh_public_key` from roks DA - there were duplicate entries and we want it hidden, not required.
Dependency updates:
- terraform-ibm-landing-zone-vpc v6.0.1 -> v7.0.1
- Required IBM terraform provider is now >= 1.52.0
Update actions:
Consumers using override.json and looking to update to this version need to:
- modify their JSON to remove `use_manual_address_prefixes` from the `vpcs` array, as this was removed in terraform-ibm-landing-zone-vpc 7.x
- add an `address_prefixes` map to all of the VPC items in the `vpcs` array. For example:
```
"address_prefixes": {
"zone-1": [],
"zone-2": [], …
```
> PR to generate 3.7.0 release

- tests/pr_test.go
Removed the ignoreUpdates for pr_test file which was added in https://github.com/terraform-ibm-modules/terraform-ibm-landing-zone/pull/431.
If a release is required, replace this text with information that users need to know about the release. Write the release notes to help users understand the changes, and include information about how to update from the previous version. 
Your notes helps the merger write the commit message for the PR that is published in the release notes for the module.
---
- Use a relevant [conventional commit](https://www.conventionalcommits.org/) message that is based on the …
> test: removed the ignoreUpdates from pr_test

- .secrets.baseline
- examples/quickstart/variables.tf
- ibm_catalog.json
- patterns/vsi/variables.tf
**VSI Quickstart:**
- updated the description of `ssh_key` and added validation to it
- fixed the `usage_template` in ibm_catalog.json, as it incorrectly referenced `ssh_public_key` instead of `ssh_key`
**VSI (standard) pattern:**
Update variable descriptions of `ssh_public_key` and `existing_ssh_key_name`
**ibm_catalog.json:**
removed all variables that we do not want to customise so catalog uses the default terraform configuration. 
If a release is required, replace this text with information that users need to know about the release. Write the release notes to help users understand the changes, …
> fix: update variable descriptions

- module-metadata.json
- service_authorizations.tf
Reduce the time_sleep length in service_authorizations.tf #437
If a release is required, replace this text with information that users need to know about the release. Write the release notes to help users understand the changes, and include information about how to update from the previous version. 
Your notes helps the merger write the commit message for the PR that is published in the release notes for the module.
---
- Use a relevant [conventional commit](https://www.conventionalcommits.org/) message that is based on the PR contents and any release notes provided by the PR author. The commit …
> fix: Reduce the time_sleep length in service_authorizations.tf

- .secrets.baseline
- ibm_catalog.json
- patterns/roks/variables.tf
- patterns/vpc/variables.tf
Replace this text with a summary of the changes in this PR. Include why the changes are needed and context about the changes. List required dependencies. If there is a Git issue for the change, please link to it.
If a release is required, replace this text with information that users need to know about the release. Write the release notes to help users understand the changes, and include information about how to update from the previous version. 
Your notes helps the merger write the commit message for the PR that is published in the release notes for the module.
---
- Use a relevant [conventional …
> ci: update json with required vars

- .secrets.baseline
- ibm_catalog.json
- patterns/roks/catalogValidationValues.json.template
- patterns/vpc/catalogValidationValues.json.template
- patterns/vsi/catalogValidationValues.json.template
Since we do not claim the controls in the standard flavours (since hpcs is not mandatory), we don't have to use hpcs for catalog validation. This resolve the issue where we currently do not have a hpcs instance in the account where we are doing validation right now.
Also explicitly marking `ssh_public_key` as required in catalog so it shows in projects UI (should not of been removed in https://github.com/terraform-ibm-modules/terraform-ibm-landing-zone/pull/454)
If a release is required, replace this text with information that users need to know about the release. Write the release notes to help …
> ci: do not use hpcs for catalog validation

- patterns/vsi/variables.tf
update the default teleport VSI image
Run the CI pipeline when the PR is ready for review and you expect tests to pass. …
> fix: update the default teleport VSI image

- cluster.tf
- module-metadata.json
Added version lifecycle change ignore
https://github.com/terraform-ibm-modules/terraform-ibm-landing-zone/issues/498
Run …
> [Fix] add version lifecycle change ignore

- reference-architectures/deploy-arch-ibm-slz-ocp.md
- reference-architectures/deploy-arch-ibm-slz-vpc-standard.md
- reference-architectures/deploy-arch-ibm-slz-vsi-quickstart.md
- reference-architectures/deploy-arch-ibm-slz-vsi-standard.md
update version and last updated date to 4.4.7 in reference architectures for IBM Cloud
Run the CI pipeline when the PR …
> docs: update ref arch for 4.4.7

- ibm_catalog.json
add dropdown menu for kube version in catalog for roks pattern
Run the CI pipeline when the PR is ready for review and …
> feat: add dropdown menu for kube version in catalog for roks pattern

- cra-tf-validate-ignore-rules.json
Update the ignore reason in cra-tf-validate-ignore-rules.json
```
/run pipeline
```
> Update the ignore reason in cra-tf-validate-ignore-rules.json

- README.md
- bastion_host.tf
- f5_vsi.tf
- module-metadata.json
- virtual_servers.tf
bump to vsi 2.5.0
```
/run pipeline
```
> fix: bump to vsi 2.5.0

- tests/other_test.go
- tests/pr_test.go
- Added HPCS tests to other_test.go so they run weekly
- Renamed the tests in pr_test.go since they use key protect, and not hpcs
```
/run pipeline
```
> test: cleanup tests

- patterns/roks/module/variables.tf
- patterns/roks/variables.tf
https://github.com/terraform-ibm-modules/terraform-ibm-landing-zone/issues/555
```
/run pipeline
```
> fix: prefix validation

- .secrets.baseline
- ibm_catalog.json
- updated the `existing_ssh_key_name` variable to be a vpc_ssh_key type in catalog so it now shows like this:
- Moved `existing_ssh_key_name` under the required variable list, and moved `ssh_public_key` into the optional section since in most cases users will be using a common ssh key (not a user private one)
I tested this config in schematcis (via projects + catalog) and it works well. The output shows this:
```
/run pipeline
```
- When merging, use a relevant [conventional commit](https://www.conventionalcommits.org/) message …
> update the `existing_ssh_key_name` variable to be a vpc_ssh_key type in catalog

- variables.tf
Issue: https://github.ibm.com/GoldenEye/issues/issues/5786
```
/run pipeline
```
> fix: invalid validation for the placement groups variable

- ibm_catalog.json
`IBM Cloud for Financial Services` has been renamed to `IBM Cloud Framework for Financial Services` so need to update profile name in the `ibm_catalog.json`
```
/run pipeline
```
- Merge by using "Squash and …
> Update profile_name in ibm_catalog.json

- patterns/roks/catalogValidationValues.json.template
- patterns/vpc/catalogValidationValues.json.template
We are hitting quota issues in our account, so splitting out regions so each DA deploys to different region in catalog validation pipeline
```
/run pipeline
```
> Update the regions used during catalog validation of DAs

- patterns/roks/outputs.tf
- patterns/vpc/outputs.tf
- patterns/vsi/outputs.tf
> fix: extend the kms output to the patterns

- reference-architectures/deploy-arch-ibm-slz-ocp.md
- reference-architectures/deploy-arch-ibm-slz-vpc-standard.md
- reference-architectures/deploy-arch-ibm-slz-vsi-quickstart.md
- reference-architectures/deploy-arch-ibm-slz-vsi-standard.md
Updates the version in the reference architectures to match the landing zone DA release.
```
/run pipeline
```
> Update reference architectures to 4.12.3

- tests/other_test.go
- tests/pr_test.go
Added schematics test for two other tests in pr_test.go
```
/run pipeline
```
> tests: add two schematics test

- .secrets.baseline
- cra-tf-validate-ignore-rules.json
- ibm_catalog.json
DAs are not designed to be embedded into part of another DA solution - they are designed to be the top level solution and not called from any higher level. So in this PR, I am removing the `usage_template` from the DA manifest which means the DA will no long show the `Embed code` section in the UI:
Once merged will look like this:
```
/run pipeline
```
- Include information that …
> ci: remove usage template from ibm_catalog.json

- .github/settings.yml
update topics
```
/run pipeline
```
> ci: update topics

- reference-architectures/deploy-arch-ibm-slz-ocp.md
- reference-architectures/deploy-arch-ibm-slz-vpc-standard.md
- reference-architectures/deploy-arch-ibm-slz-vsi-quickstart.md
- reference-architectures/deploy-arch-ibm-slz-vsi-standard.md
To match deployable architecture release in IBM Cloud
```
/run pipeline
```
> docs: update RAs to v4.13.3

- ibm_catalog.json
> Add provider name to ibm_catalog.json

- atracker.tf
- variables.tf
Support for Madrid DC.
Add support for Madrid DC, eu-es.
```
/run pipeline
```
> Support for Madrid DC, eu-es

- ibm_catalog.json
production version 4.13.3 and 4.12.3 have been patched with this update so updating the code to match
```
/run pipeline
```
> Make `ssh_public_key` required and `existing_ssh_key_name` optional

- README.md
- bastion_host.tf
- f5_vsi.tf
- main.tf
- patterns/vsi-extension/main.tf
- patterns/vsi-extension/variables.tf
- virtual_servers.tf
Issue : https://github.ibm.com/GoldenEye/issues/issues/6474
```
/run pipeline
```
> fix: update terraform-modules and duplicate auth policy

- patterns/vsi-extension/README.md
- patterns/vsi-extension/variables.tf
Merges into `cleanup` branch
- provides more information about variables. Links should be rendered in the catalog UI
- Pushes most of the readme information to Cloud docs.
```
/run pipeline
```
> update variable desc and readme

- reference-architectures/deploy-arch-ibm-slz-ocp.md
- reference-architectures/deploy-arch-ibm-slz-vpc-standard.md
- reference-architectures/deploy-arch-ibm-slz-vsi-quickstart.md
- reference-architectures/deploy-arch-ibm-slz-vsi-standard.md
> docs: update reference-architectures version to 5.1.0

- renovate.json
Revert the change made in this PR: https://github.com/terraform-ibm-modules/terraform-ibm-landing-zone/pull/626
Since, we no longer need this change
```
/run pipeline
```
> revert: ignorePaths change

- reference-architectures/deploy-arch-ibm-slz-vsi-extension.md
Changes the URL from the VPC landing zone catalog details to the VSI on VPC landing zone details.
The output is a "Configure and deploy" link in the reference architecture in Cloud docs. https://cloud.ibm.com/docs/secure-infrastructure-vpc?topic=secure-infrastructure-vpc-vsi-ext-ra
```
/run pipeline
```
- Include information that users need to know about the PR in the commit …
> docs: fix deployment URL for extension RA

- patterns/roks/module/variables.tf
- patterns/roks/variables.tf
- patterns/vpc/module/variables.tf
- patterns/vpc/variables.tf
Update VSI image name variable defaults to ibm-ubuntu-22-04-3-minimal-amd64-2
> fix: update the default VSI image name to ibm-ubuntu-22-04-3-minimal-amd64-2

- .catalog-onboard-pipeline.yaml
Update .catalog-onboard-pipeline.yaml so validation is now done with Projects
```
/run pipeline
```
> Update .catalog-onboard-pipeline.yaml so validation is now done with Projects

- README.md
- patterns/roks/README.md
Added to readme for use in GH. Added to ROKS pattern so that it displays in the Cloud catalog, although the content might be coming from the manifest or from a UI override.
```
/run pipeline
```
> add cluster update note

- .catalog-onboard-pipeline.yaml
- ibm_catalog.json
- patterns/roks-quickstart/catalogValidationValues.json.template
onboard to roks quickstart to catalog
```
/run pipeline
```
> onboard roks quickstart to catalog

- reference-architectures/deploy-arch-ibm-slz-ocp-quickstart.md
- reference-architectures/deploy-arch-ibm-slz-ocp.md
- reference-architectures/deploy-arch-ibm-slz-vpc-standard.md
- reference-architectures/deploy-arch-ibm-slz-vsi-extension.md
- reference-architectures/deploy-arch-ibm-slz-vsi-quickstart.md
- reference-architectures/deploy-arch-ibm-slz-vsi-standard.md
- Include new ROKS quickstart ref arch by setting production to true.
- Minor editorial updates on ocp-quickstart. @toddgiguere please check.
- Update dates and versions
```
/run pipeline
```
> Update reference architectures for 5.20.0 release

- examples/one-vpc-one-vsi/override.json
- examples/override-example/override.json
- patterns/mixed/override.json
- patterns/mixed/variables.tf
- patterns/roks/module/variables.tf
- patterns/roks/variables.tf
- patterns/vpc/module/variables.tf
- patterns/vpc/variables.tf
- patterns/vsi-extension/variables.tf
- patterns/vsi-quickstart/variables.tf
- patterns/vsi/module/variables.tf
- patterns/vsi/override.json
- patterns/vsi/variables.tf
Update VSI image name variable defaults to ibm-ubuntu-22-04-4-minimal-amd64-1
> fix: update the default VSI image name to ibm-ubuntu-22-04-4-minimal-amd64-1

- cra-config.yaml
- ibm_catalog.json
update DAs to claim SCC profile "IBM Cloud Framework for Financial Services" version 1.6.0
(NOTE: The name of the profile changed since 1.3.0)
```
/run pipeline
```
> update DAs to claim SCC profile "IBM Cloud Framework for Financial Services" version 1.6.0

- reference-architectures/deploy-arch-ibm-slz-ocp-quickstart.md
- reference-architectures/deploy-arch-ibm-slz-ocp.md
- reference-architectures/deploy-arch-ibm-slz-vpc-standard.md
- reference-architectures/deploy-arch-ibm-slz-vsi-extension.md
- reference-architectures/deploy-arch-ibm-slz-vsi-quickstart.md
- reference-architectures/deploy-arch-ibm-slz-vsi-standard.md
updated version information and lastupdated dates in the reference architectures.
```
/run pipeline
```
> Update ref arch for v5.21.0

- examples/one-vpc-one-vsi/override.json
- examples/override-example/override.json
- patterns/mixed/override.json
- patterns/mixed/variables.tf
- patterns/roks/module/variables.tf
- patterns/roks/variables.tf
- patterns/vpc/module/variables.tf
- patterns/vpc/variables.tf
- patterns/vsi-extension/variables.tf
- patterns/vsi-quickstart/variables.tf
- patterns/vsi/module/variables.tf
- patterns/vsi/override.json
- patterns/vsi/variables.tf
Update VSI image name variable defaults to ibm-ubuntu-24-04-minimal-amd64-1
> fix: update the default VSI image name to ibm-ubuntu-24-04-minimal-amd64-1

- patterns/mixed/variables.tf
- patterns/roks-quickstart/variables.tf
- patterns/roks/variables.tf
also fix grammar.
didn't change the variable names that use the spelling, just the descriptions.
```
/run pipeline
```
> Update license spelling

- patterns/roks-quickstart/version.tf
update version.tf in roks quickstart to allow tf 1.6
```
/run pipeline
```
> fix: update version.tf in roks quickstart to allow tf 1.6

- reference-architectures/deploy-arch-ibm-slz-ocp-quickstart.md
- reference-architectures/deploy-arch-ibm-slz-ocp.md
- reference-architectures/deploy-arch-ibm-slz-vpc-standard.md
- reference-architectures/deploy-arch-ibm-slz-vsi-extension.md
- reference-architectures/deploy-arch-ibm-slz-vsi-quickstart.md
- reference-architectures/deploy-arch-ibm-slz-vsi-standard.md
Update reference architecture Markdown files to v5.24.5 and release date of 2024-06-12
```
/run pipeline
```
> update ref arch to 5.24.5

- README.md
- main.tf
- outputs.tf
- patterns/mixed/outputs.tf
- patterns/roks-quickstart/outputs.tf
- patterns/roks/module/outputs.tf
- patterns/roks/outputs.tf
- patterns/vpc/module/outputs.tf
- patterns/vpc/outputs.tf
- patterns/vsi/module/outputs.tf
- patterns/vsi/outputs.tf
upgrade landing-zone-vpc to latest version and expose the DNS outputs added in the root and all patterns
related issue: https://github.com/terraform-ibm-modules/terraform-ibm-landing-zone/issues/832
```
/run pipeline
```
- Use the …
> feat: expose DNS outputs

- variables.tf
Resolves: https://github.com/terraform-ibm-modules/terraform-ibm-landing-zone/issues/843
```
/run pipeline
```
> fix: update cos plan 

- reference-architectures/deploy-arch-ibm-slz-ocp-quickstart.md
- reference-architectures/deploy-arch-ibm-slz-ocp.md
- reference-architectures/deploy-arch-ibm-slz-vpc-standard.md
- reference-architectures/deploy-arch-ibm-slz-vsi-extension.md
- reference-architectures/deploy-arch-ibm-slz-vsi-quickstart.md
- reference-architectures/deploy-arch-ibm-slz-vsi-standard.md
Update reference architectures to 5.29.0 release
```
/run pipeline
```
> Update ref arch to new release

- reference-architectures/deploy-arch-ibm-slz-ocp-quickstart.md
- reference-architectures/deploy-arch-ibm-slz-ocp.md
- reference-architectures/deploy-arch-ibm-slz-vpc-standard.md
- reference-architectures/deploy-arch-ibm-slz-vsi-extension.md
- reference-architectures/deploy-arch-ibm-slz-vsi-quickstart.md
- reference-architectures/deploy-arch-ibm-slz-vsi-standard.md
update date and version
```
/run pipeline
```
> Update reference architectures for v5.31.2

- .catalog-onboard-pipeline.yaml
Projects currently unstable, so switch to schematics for validation
```
/run pipeline
```
> Update .catalog-onboard-pipeline.yaml to use schematics validation

- reference-architectures/deploy-arch-ibm-slz-ocp-quickstart.md
- reference-architectures/deploy-arch-ibm-slz-ocp.md
- reference-architectures/deploy-arch-ibm-slz-vpc-standard.md
- reference-architectures/deploy-arch-ibm-slz-vsi-extension.md
- reference-architectures/deploy-arch-ibm-slz-vsi-quickstart.md
- reference-architectures/deploy-arch-ibm-slz-vsi-standard.md
> docs: update ref arch to 6.0.1

- ibm_catalog.json
> fix: update VSI extension DA to claim fscloud 1.7.0

- reference-architectures/deploy-arch-ibm-slz-ocp-quickstart.md
- reference-architectures/deploy-arch-ibm-slz-ocp.md
- reference-architectures/deploy-arch-ibm-slz-vpc-standard.md
- reference-architectures/deploy-arch-ibm-slz-vsi-extension.md
- reference-architectures/deploy-arch-ibm-slz-vsi-quickstart.md
- reference-architectures/deploy-arch-ibm-slz-vsi-standard.md
update version in reference-architectures since version 6.6.0 will go live today
```
/run pipeline
```
> docs: update version in reference-architectures

- outputs.tf
> fix: invalid index for rg output values when override set to true

- examples/one-vpc-one-vsi/override.json
- examples/override-example/override.json
- patterns/mixed/override.json
- patterns/mixed/variables.tf
- patterns/roks/module/variables.tf
- patterns/roks/variables.tf
- patterns/vpc/module/variables.tf
- patterns/vpc/variables.tf
- patterns/vsi-extension/variables.tf
- patterns/vsi-quickstart/variables.tf
- patterns/vsi/module/variables.tf
- patterns/vsi/override.json
- patterns/vsi/variables.tf
Update VSI image name variable defaults to ibm-ubuntu-24-04-6-minimal-amd64-2
> fix: update the default VSI image name to ibm-ubuntu-24-04-6-minimal-amd64-2

- .catalog-onboard-pipeline.yaml
projects validation required when ansible migration script present in code
```
/run pipeline
```
> ci: update catalog validation to validate using projects

- .catalog-onboard-pipeline.yaml
> ci: change back to using schematics for catalog validation

- patterns/DA-cbr-tutorial.md
- Few markdown updates.
- Addressing the diagram alignment issues in this [PR](https://github.com/terraform-ibm-modules/terraform-ibm-landing-zone/pull/976)
```
/run pipeline
```
> docs: Fix cbr docs diagram alignment.

- examples/one-vpc-one-vsi/override.json
- examples/override-example/override.json
- patterns/mixed/override.json
- patterns/mixed/variables.tf
- patterns/roks/module/variables.tf
- patterns/roks/variables.tf
- patterns/vpc/module/variables.tf
- patterns/vpc/variables.tf
- patterns/vsi-extension/variables.tf
- patterns/vsi-quickstart/variables.tf
- patterns/vsi/module/variables.tf
- patterns/vsi/override.json
- patterns/vsi/variables.tf
Update VSI image name variable defaults to ibm-ubuntu-24-04-2-minimal-amd64-4
> fix: update the default VSI image name to ibm-ubuntu-24-04-2-minimal-amd64-4

- ibm_catalog.json
Update dropdown box with values. Reference values https://github.com/terraform-ibm-modules/terraform-ibm-base-ocp-vpc/blob/main/ibm_catalog.json
```
/run pipeline
```
> fix: update ibm_catalog json to use dropdown picker

- examples/one-vpc-one-vsi/override.json
- examples/override-example/override.json
- patterns/mixed/override.json
- patterns/mixed/variables.tf
- patterns/roks/module/variables.tf
- patterns/roks/variables.tf
- patterns/vpc/module/variables.tf
- patterns/vpc/variables.tf
- patterns/vsi-extension/variables.tf
- patterns/vsi-quickstart/variables.tf
- patterns/vsi/module/variables.tf
- patterns/vsi/override.json
- patterns/vsi/variables.tf
Update VSI image name variable defaults to ibm-ubuntu-24-04-2-minimal-amd64-5
> fix: update the default VSI image name to ibm-ubuntu-24-04-2-minimal-amd64-5

- examples/one-vpc-one-vsi/override.json
- examples/override-example/override.json
- patterns/mixed/override.json
- patterns/mixed/variables.tf
- patterns/roks/module/variables.tf
- patterns/roks/variables.tf
- patterns/vpc/module/variables.tf
- patterns/vpc/variables.tf
- patterns/vsi-extension/variables.tf
- patterns/vsi-quickstart/variables.tf
- patterns/vsi/module/variables.tf
- patterns/vsi/override.json
- patterns/vsi/variables.tf
Update VSI image name variable defaults to ibm-ubuntu-24-04-3-minimal-amd64-2
> fix: update the default VSI image name to ibm-ubuntu-24-04-3-minimal-amd64-2
